# Generated by Django 2.0.1 on 2018-06-16 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=30)),
                ('auth_token', models.TextField()),
                ('timeline_token', models.TextField(max_length=255)),
                ('qrcodeurl', models.URLField()),
                ('mid', models.CharField(max_length=255)),
                ('Name', models.TextField(blank=True, max_length=255)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('name', models.TextField(max_length=255)),
                ('text', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('msgid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=2)),
                ('packageid', models.CharField(max_length=30)),
                ('stickerid', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='message_msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_mid', models.TextField(max_length=255)),
                ('to_mid', models.TextField()),
                ('createdTime', models.TextField(editable=False)),
                ('deliveredTime', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=255)),
                ('location', models.TextField(max_length=255)),
                ('hasContent', models.BooleanField()),
                ('contentType', models.TextField(max_length=255)),
                ('contentPreview', models.TextField(max_length=255)),
                ('contentMetadata', models.TextField(max_length=255)),
                ('sessionId', models.CharField(max_length=30)),
                ('chunks', models.TextField(max_length=255)),
                ('relatedMessageId', models.TextField(max_length=255)),
                ('messageRelationType', models.TextField(max_length=255)),
                ('readCount', models.TextField(max_length=255)),
                ('relatedMessageServiceCode', models.TextField(max_length=255)),
                ('result_code', models.TextField(max_length=100)),
                ('result_msg', models.TextField()),
                ('msgid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoints.message')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField(blank=True)),
                ('phone', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('regionCode', models.CharField(max_length=30)),
                ('displayName', models.TextField(blank=True, max_length=255)),
                ('phoneticName', models.TextField(blank=True, max_length=255)),
                ('pictureStatus', models.TextField(blank=True, max_length=255)),
                ('thumbnailUrl', models.URLField(blank=True)),
                ('statusMessage', models.TextField(blank=True, max_length=255)),
                ('allowSearchByUserid', models.BooleanField(max_length=255)),
                ('allowSearchByEmail', models.BooleanField(max_length=255)),
                ('picturePath', models.TextField(blank=True, max_length=255)),
                ('musicProfile', models.TextField(blank=True, max_length=255)),
                ('videoProfile', models.TextField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoints.account')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='timeline',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='slug')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timelineid', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('picture', models.ImageField(upload_to='./upload/images/')),
                ('stickerID', models.CharField(max_length=30)),
                ('packageID', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='timeline_msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('code', models.TextField(max_length=100)),
                ('message', models.TextField(max_length=100)),
                ('result', models.TextField()),
                ('writerMid', models.TextField()),
                ('appSn', models.TextField()),
                ('homeId', models.TextField()),
                ('postId', models.TextField()),
                ('status', models.TextField()),
                ('likeCount', models.CharField(max_length=30)),
                ('commentCount', models.CharField(max_length=30)),
                ('postInfo_msg', models.TextField()),
                ('timelineid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoints.timeline')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
