# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usermanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfomation',
            name='special_list',
        ),
    ]
