# Generated by Django 2.0.1 on 2018-06-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pinCode',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
