# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_id', models.CharField(max_length=200)),
                ('acc_pwd', models.CharField(max_length=200)),
                ('ip_last', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('group_type', models.IntegerField(default=1)),
                ('group_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=200)),
                ('ip_reg', models.CharField(max_length=200)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usermanager.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='acc_grp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usermanager.Group'),
        ),
    ]
