# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usermanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='acc_grp',
            new_name='account_group',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='acc_id',
            new_name='account_id',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='acc_pwd',
            new_name='account_password',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='ip_last',
            new_name='last_join',
        ),
        migrations.RenameField(
            model_name='userinfomation',
            old_name='ip_reg',
            new_name='ip_register',
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_type',
        ),
        migrations.RemoveField(
            model_name='group',
            name='id',
        ),
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
